platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

def swinject_pods
    pod 'Swinject'
end

def helpers_pods
    pod 'R.swift'
    pod "OBD2-Swift"
end

def ui_helpers_pods
    pod 'SnapKit', '~> 4.0.0'
end

target 'AudiOBD2Scanner' do
        
    swinject_pods
    helpers_pods
    ui_helpers_pods
end
